import { fixture, html, expect, oneEvent } from '@open-wc/testing';
import '../granite-json-tree-viewer.js';

describe('granite-json-tree-viewer', () => {
  it('renders a tree from the data attribute', async () => {
    const element = await fixture(html`
      <granite-json-tree-viewer
          data='{"firstName":"John","phones":["123-45-67"]}'></granite-json-tree-viewer>
    `);

    const tree = element.shadowRoot.querySelector('.jsontree_tree');
    expect(tree).to.exist;

    const labels = [...element.shadowRoot.querySelectorAll('.jsontree_label')]
      .map((el) => el.textContent);
    expect(labels).to.include('"firstName"');
    expect(labels).to.include('"phones"');

    const values = [...element.shadowRoot.querySelectorAll('.jsontree_value_string')]
      .map((el) => el.textContent);
    expect(values).to.include('"John"');
    expect(values).to.include('"123-45-67"');
  });

  it('renders a tree from a data property set imperatively', async () => {
    const element = await fixture(html`<granite-json-tree-viewer></granite-json-tree-viewer>`);
    expect(element.shadowRoot.querySelector('.jsontree_tree')).to.not.exist;

    element.data = { answer: 42 };
    await element.updateComplete;

    const value = element.shadowRoot.querySelector('.jsontree_value_number');
    expect(value).to.exist;
    expect(value.textContent).to.equal('42');
  });

  it('escapes HTML in keys and values (XSS, summerstyle/jsonTreeViewer#21)', async () => {
    const element = await fixture(html`<granite-json-tree-viewer></granite-json-tree-viewer>`);
    // '\x3C' === '<': a literal closing script tag in the source would
    // break the HTML test page generated by the test runner
    const scriptPayload = '\x3Cscript>alert(2)\x3C/script>';
    element.data = {
      '<img src=x onerror=alert(1)>': scriptPayload,
      nested: { '<em>key</em>': ['<i>value</i>'] },
    };
    await element.updateComplete;

    // No element from the payloads may exist in the rendered DOM.
    // (`<b>` is not checked: the tree renders the {}/[] braces in <b> tags.)
    expect(element.shadowRoot.querySelector('img'), 'img').to.be.null;
    expect(element.shadowRoot.querySelector('script'), 'script').to.be.null;
    expect(element.shadowRoot.querySelector('em'), 'em').to.be.null;
    expect(element.shadowRoot.querySelector('i'), 'i').to.be.null;

    // The payloads must be displayed as escaped text
    const text = element.shadowRoot.querySelector('.jsontree_tree').textContent;
    expect(text).to.include('<img src=x onerror=alert(1)>');
    expect(text).to.include(scriptPayload);
    expect(text).to.include('<em>key</em>');
    expect(text).to.include('<i>value</i>');
  });

  it('preserves key insertion order by default', async () => {
    const element = await fixture(html`<granite-json-tree-viewer></granite-json-tree-viewer>`);
    element.data = { zebra: 1, alpha: 2, mango: 3 };
    await element.updateComplete;

    const labels = [...element.shadowRoot.querySelectorAll('.jsontree_label')]
      .map((el) => el.textContent);
    expect(labels).to.deep.equal(['"zebra"', '"alpha"', '"mango"']);
  });

  it('sorts keys alphabetically with sort-keys', async () => {
    const element = await fixture(html`
      <granite-json-tree-viewer sort-keys></granite-json-tree-viewer>
    `);
    element.data = { zebra: 1, alpha: 2, mango: 3 };
    await element.updateComplete;

    const labels = [...element.shadowRoot.querySelectorAll('.jsontree_label')]
      .map((el) => el.textContent);
    expect(labels).to.deep.equal(['"alpha"', '"mango"', '"zebra"']);
  });

  it('expands and collapses nodes', async () => {
    const element = await fixture(html`<granite-json-tree-viewer></granite-json-tree-viewer>`);
    element.data = { nested: { deep: { value: 1 } } };
    await element.updateComplete;

    const expandedCount = () =>
      element.shadowRoot.querySelectorAll('.jsontree_node_expanded').length;

    // Only the root is expanded initially
    expect(expandedCount()).to.equal(1);

    element.expand();
    expect(expandedCount()).to.equal(3);

    element.collapse();
    expect(expandedCount()).to.equal(1);
  });

  it('toggles a node on label click', async () => {
    const element = await fixture(html`<granite-json-tree-viewer></granite-json-tree-viewer>`);
    element.data = { nested: { value: 1 } };
    await element.updateComplete;

    const label = [...element.shadowRoot.querySelectorAll('.jsontree_label')]
      .find((el) => el.textContent.includes('"nested"'));
    const node = label.closest('.jsontree_node_complex');

    expect(node.classList.contains('jsontree_node_expanded')).to.be.false;
    label.click();
    expect(node.classList.contains('jsontree_node_expanded')).to.be.true;
    label.click();
    expect(node.classList.contains('jsontree_node_expanded')).to.be.false;
  });

  it('fires jsontree-jsonpath on shift+click instead of alert()', async () => {
    const element = await fixture(html`<granite-json-tree-viewer></granite-json-tree-viewer>`);
    element.data = { nested: { phones: ['123'] } };
    await element.updateComplete;
    element.expand();

    const label = [...element.shadowRoot.querySelectorAll('.jsontree_label')]
      .find((el) => el.textContent.includes('"phones"'));

    setTimeout(() => {
      label.dispatchEvent(new MouseEvent('click', { shiftKey: true, bubbles: true }));
    });
    const { detail } = await oneEvent(element, 'jsontree-jsonpath');

    expect(detail.path).to.equal('$["nested"]["phones"]');
    expect(detail.dotPath).to.equal('$.nested.phones');
  });

  it('returns the source JSON with toSourceJSON', async () => {
    const element = await fixture(html`<granite-json-tree-viewer></granite-json-tree-viewer>`);
    const data = { a: 2, b: [1, 2] };
    element.data = data;
    await element.updateComplete;

    expect(element.toSourceJSON()).to.equal('{"a":2,"b":[1,2]}');
    expect(element.toSourceJSON(true)).to.equal(JSON.stringify(data, null, 4));
  });

  it('throws on a non-object/array root', async () => {
    const element = await fixture(html`<granite-json-tree-viewer></granite-json-tree-viewer>`);
    element.data = 'just a string';
    let error = null;
    try {
      await element.updateComplete;
    } catch (e) {
      error = e;
    }
    expect(error).to.be.an.instanceOf(TypeError);
  });

  it('clears the tree when data is set to null', async () => {
    const element = await fixture(html`<granite-json-tree-viewer></granite-json-tree-viewer>`);
    element.data = { a: 1 };
    await element.updateComplete;
    expect(element.shadowRoot.querySelector('.jsontree_tree')).to.exist;

    element.data = null;
    await element.updateComplete;
    expect(element.shadowRoot.querySelector('.jsontree_tree')).to.not.exist;
    expect(element.tree).to.be.null;
  });
});
